### ISSUE TITLE
Python SSL bug

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [TCLRainbow/DimBot#1]
https://github.com/aio-libs/aiohttp/issues/3535

**Comment by Pythonic-Rainbow** [comment]
Update Python to 3.7.4 and this will be fixed

**Comment by Pythonic-Rainbow** [comment]
https://github.com/aio-libs/aiohttp/issues/3535

**Comment by ChingDim** [comment]
Updated to Py 3.7.4
