### ISSUE TITLE
Clean database

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [TCLRainbow/DimBot#61]
Due to a misconception of how ROWID works, Echo has something that has to be changed.

e.g. if DimBot leaves a guild, should wipe the database rows related to it.

Also should defragment Quote when DimBot boots
Asks confirmation when someone deletes quote.

**Comment by Pythonic-Rainbow** [comment]
Implemented on_guild_leave()

**Comment by Pythonic-Rainbow** [comment]
Implemented confirmation check

**Comment by feudalism1** [comment]
thanks i love you no homo

**Comment by Pythonic-Rainbow** [comment]
Completed in https://github.com/TCLRainbow/DimBot/commit/95337cb8c6ae3cd9870292ba14eb047f41e1c816
